# Numerical analysis: TP-1
<h4 align="right"> Author: <i> Hicham Janati </i></h4>

In [1]:
import numpy as np

#### 1) Integers and floating point representations
run the following cells below.

In [28]:
a = 2 * np.ones(1).astype('int64')
print(f"a is equal to {a} and its type is {a.dtype}.")

a is equal to [2] and its type is int64.


In [31]:
for i in range(60, 68):
    print(f"2 ** {i} = {a ** i}")


2 ** 60 = [1152921504606846976]
2 ** 61 = [2305843009213693952]
2 ** 62 = [4611686018427387904]
2 ** 63 = [-9223372036854775808]
2 ** 64 = [0]
2 ** 65 = [0]
2 ** 66 = [0]
2 ** 67 = [0]


**Q1.  Can you explain the observed behavior ?  Propose a way to fix this.**

The number is code with 64 bits with the first bits deciding on the sign of the number

**Q2. Does the problem occur without specifying the dtype `np.ones(1)`? Deduce a real numpy usecase where this might be a problem.**

In [35]:
a = 2 * np.ones(1)
print(f"a is equal to {a} and its type is {a.dtype}.")

for i in range(60, 68):
    print(f"2 ** {i} = {a ** i}")

print(a**64 +1 - a**64) 
print('But 2**64 + 1 - 2**64 = 1, so the result is incorrect.')

a is equal to [2.] and its type is float64.
2 ** 60 = [1.1529215e+18]
2 ** 61 = [2.30584301e+18]
2 ** 62 = [4.61168602e+18]
2 ** 63 = [9.22337204e+18]
2 ** 64 = [1.84467441e+19]
2 ** 65 = [3.68934881e+19]
2 ** 66 = [7.37869763e+19]
2 ** 67 = [1.47573953e+20]
[0.]
But 2**64 + 1 - 2**64 = 1, so the result is incorrect.


 In deep learning applications, chosing the "right" dtype is a very important tradeoff between speed and accuracy.

#### 2) Imperfect floating point numbers 

Consider the function $f(x) = 2x$ on $[0, 0.5]$ and $f(x) = 2x - 1$ on $]0.5, 1]$ 

**Q1.** Consider the sequence defined by $x_{n+1} = f(x_n)$ with $x_0 = 0.1$ Compute the first 5 elements of the sequence (manually). What do you conclude ?

x1 = 0.1 
0.2 0.4 0.8 1.6

**Q2.** Complete the function below that returns $x_n$. What do you observe ?

In [67]:
x0 = 0.1

def f(x, n=100):
    for i in range(n):
        if 0<= x <= 0.5:
                x = 2 * x
        else:
            x = 2*x - 1
        #print(x)
    return x

f(x0)

1.0

`float64` numbers are represented using 64 bits as:
$$(-1)^s \quad 0.m_1..m_{52} \quad 2^{e_1..e_{11}}$$
where $s$ is a sign bit, $m$ is the mantissa (52 bits) and $e$ is the exponent (11 bits)

**Q4** Take a moment a contemplate this mystery. Use the `pretty_float_bits` function below to find an explanation for this.

https://evanw.github.io/float-toy/

In [49]:
0.1 + 0.2

0.30000000000000004

In [80]:
import struct

def float_to_bin(f) -> str:
    fmt = ">d"
    bz = struct.pack(fmt, f)
    return "".join(f"{b:08b}" for b in bz)

def sign_exponent_fraction(s):
    return s[0:1], s[1:12], s[12:64]

def pretty_float_bits(f) -> str:
    return " ".join(sign_exponent_fraction(float_to_bin(f)))

pretty_float_bits(0.2)

'0 01111111100 1001100110011001100110011001100110011001100110011010'

In [79]:
print(pretty_float_bits(0.1))
print('0.1 is an approximation in binary, so the result is not exact.')

0 01111111011 1001100110011001100110011001100110011001100110011010
0.1 is an approximation in binary, so the result is not exact.


In [47]:
pretty_float_bits(0.1 + 0.2)

'0 01111111101 0011001100110011001100110011001100110011001100110100'

In [68]:
pretty_float_bits(0.3)

'0 01111111101 0011001100110011001100110011001100110011001100110011'

In [82]:
pretty_float_bits(1.0)

'0 01111111111 0000000000000000000000000000000000000000000000000000'

In [83]:
pretty_float_bits(2.0)

'0 10000000000 0000000000000000000000000000000000000000000000000000'

In [84]:
pretty_float_bits(3.0)

'0 10000000000 1000000000000000000000000000000000000000000000000000'

With floats, the order matters:

In [69]:
100. - 100. + 0.1

0.1

In [70]:
0.1 + 100. - 100.

0.09999999999999432

In [71]:
one = np.ones(1)

In [72]:
one*0

array([0.])

In [73]:
-one*0

array([-0.])

In [74]:
one/0

C:\Users\samai\AppData\Local\Temp\ipykernel_7984\687095102.py:1: RuntimeWarning: divide by zero encountered in divide
  one/0


array([inf])

In [76]:
np.inf - np.inf

nan

#### 3) Machine precision and cumulative errors

Consider the integral $$I_n = \int_{0}^1 \frac{x^n}{x + 10}dx$$

1. Without computing $I_n$, find its limit.
2. Compute $I_0$ and find a recurrence formula between $I_{n+1}$ and $I_n$
3. If we were to compute $I_n$ recursively, would that algorithm be stable numerically ?

lim = 0


In [ ]:
def integral(i0, n):
    ii = i0
    for jj in range(n):

    return ii

In [ ]:
integral(np.log(11/10), 20)

4. Replace 10 in the integral with a constant A > 1. Given a machine precision variable $\varepsilon$, how can we set the number of iterations $n$ based on a desired cumulative error E ?

In [85]:
print(np.finfo(float).eps) 

2.220446049250313e-16


**Independent questions:**

**Q5.** Write a piece of code that can find $\varepsilon$ numerically. 



In [91]:
eps = 1.0
while 1.0 + eps > 1.0:
    eps = eps / 2.0

print(eps)
eps*10**(-100)

1.1102230246251565e-16


1.1102230246251566e-116

**Q6.** Given what you know now, how should you test if two numbers or arrays are equal ? 

#### 4) Logsum-exp trick
Consider a classification model with 4 classes. We are modeling the probablity of a sample being in class $k$ with: $$p_k = \frac{ exp(w_k)}{\sum_{i=1}^{4} exp(w_i)}$$

where $w$ are the weights of a neural net.
1. Why does this model make sense ? 
2. Given the example $w = [-20, -1, 0, 1000]$, it is obvious which class this sample should correspond to. Compute the prediction probabilities using the function below for this particular example. Explain.

In [ ]:
def predict(w):
    p = np.exp(w)
    p /= p.sum()
    return p

w = np.array([10, -1, 40, 2, 1000])
predict(w)

3. Even if we assume that $exp(w_k)$ do not overflow, computing the normalizing sum can cause problems if the number of labels is too large. After showing the following statement, propose a method to modify `predict` in order to avoid overflow errors:
$$ \forall c \in \mathbb{R} \qquad log\left(\sum_{k=1}^K exp(w_k + c)\right) =  c + log\left(\sum_{k=1}^K exp(w_k)\right) $$ 

In [ ]:
def lse(w):

    return ll

def predict_stable(w):
    return 

In [ ]:
predict_stable(w)

4. Generate random weight vectors with `np.random.randn(K)` and test that both functions return the same probabilities. Test it with the scipy `logsumexp`: 

In [ ]:
from scipy.special import logsumexp
